const testCase = (name, area, smoke = false) => ({
  name,
  area,
  smoke,
  disposableWorld: true,
  steps: [{ workflow: name }],
});

export const fullCases = [
  testCase('runtime-api-crud', 'api', true),
  testCase('parser-native-item', 'parsing', true),
  testCase('parser-advanced-syntax', 'parsing'),
  testCase('parser-locales', 'parsing'),
  testCase('parser-structured-and-effect-only', 'parsing'),
  testCase('initial-save-failure', 'lifecycle', true),
  testCase('initial-save-resisted', 'lifecycle'),
  testCase('stage-advance-and-recovery', 'lifecycle'),
  testCase('manual-stage-and-incapacitation', 'lifecycle'),
  testCase('multiple-exposure-and-virulent', 'lifecycle'),
  testCase('onset-world-time', 'timers'),
  testCase('maximum-duration', 'timers'),
  testCase('stage-effect-rules', 'effects', true),
  testCase('persistent-condition-lifetime', 'effects'),
  testCase('advanced-stage-effects', 'effects'),
  testCase('actor-immunity', 'immunity'),
  testCase('source-immunity-bypass', 'immunity'),
  testCase('edited-definition', 'editor'),
  testCase('custom-icon-and-stage-editor', 'editor'),
  testCase('treatment-result', 'recovery'),
  testCase('counteract-result', 'recovery'),
  testCase('recovery-restrictions', 'recovery'),
  testCase('feat-adjustments', 'rules'),
  testCase('vishkanya-venom', 'rules'),
  testCase('weapon-coating-lifecycle', 'coatings'),
  testCase('weapon-injection-lifecycle', 'coatings'),
  testCase('double-poison-and-weapon-rules', 'coatings'),
  testCase('unlinked-token-storage', 'storage'),
  testCase('combat-scheduled-save', 'combat'),
  testCase('off-scene-actor-storage', 'storage'),
  testCase('chat-message-privacy', 'privacy'),
  testCase('manager-gm-ui', 'ui', true),
  testCase('player-coating-access', 'ui'),
  testCase('token-indicator', 'ui'),
  testCase('monitor-ui', 'ui'),
  testCase('region-behavior-registration', 'regions'),
  testCase('region-runtime-application', 'regions'),
  testCase('settings-persistence', 'settings'),
  testCase('visioner-stage-integration', 'integrations'),
  testCase('optional-integration-contracts', 'integrations'),
  testCase('foundry14-pf2e-compatibility', 'environment', true),
];

export const smokeCases = fullCases.filter(testCase => testCase.smoke);
